### ISSUE TITLE
Crash when Loading World

### ISSUE THREAD

**Issue by DarianLStephens** [magneticflux-/fabric-mumblelink-mod#41] opened 2020-12-27 00:11 UTC
Everything seemed to be going fine (I was able to edit the settings and such), until I tried to load a world, where it crashed with mouseclick and rendering errors?

https://pastebin.com/ZTrWWRPc

Something I found odd was that, upon adding Mumble Link, I apparently gained an extra 8 mods to my load order, as the loaded mods went from 36 to 44.

**Comment by magneticflux-** [comment] 2020-12-27 01:17
Very strange! I do stuff with AWT because I need to open URIs, but that shouldn't affect mouse click events or GLFW...

The extra mods are probably just Kotlin libraries and the config library. I'm planning on moving to Fiber Config like I did for `fabric-tree-chopper` eventually, which is more modern and should stay updated.

I'll take a look at this in a few hours, it shouldn't be too much of a hassle to fix.

**Comment by magneticflux-** [comment] 2020-12-27 20:12
Are you able to reproduce it consistently? Does it occur with only `fabric-mumblelink-mod` installed?

It looks to me like an issue in loading datafixers for world loading, which this mod doesn't touch at all. I'm inclined to believe it's something else's fault unless it's reproducible and isolated to just this mod.

**Comment by DarianLStephens** [comment] 2020-12-28 00:50
I'm able to load the game perfectly normally if I remove Mumble Link, though I haven't tried with _only_ Mumble Link.

**Comment by magneticflux-** [comment] 2020-12-28 04:43
Okay, I need this information:
- Can you reproduce it consistently? Does it happen every time you load a certain world?
- Does it occur with only the mod installed? (You can make a backup of the world if you have item- or block-adding mods)

**Comment by DarianLStephens** [comment] 2020-12-28 08:47
1. So far, the crash has been perfectly consistent. The game will crash when loading a world with the mod, and won't without it.
2. It actually does not occur with just this mod installed; it's likely some sort of odd conflict with another.

**Comment by magneticflux-** [comment] 2020-12-28 17:22
>2. It actually does not occur with just this mod installed; it's likely some sort of odd conflict with another.

That's what I expected. Could you go through your modlist using the binary search technique https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a and report the results? Fixing the issue will go _much_ faster when I know which mod is conflicting and I can read through its sources.

**Comment by DarianLStephens** [comment] 2020-12-30 18:51
Interesting; I'm no longer getting any kind of crash, whether from loading an old world or creating a new one.
My best guess in this case is that it had something to do with either Charm, Charmonium, or Strange, seeing as I updated all three before testing again.

Well, I'll be looking forward to the config rework then, whenever it should come.

**Comment by griffin4cats** [comment] 2021-08-19 00:31
Related to the AWT thing:
It also makes this mod incompatible with The Backrooms mod.
And I'm getting another disconnect in 1.17 on a mostly vanilla server, so there may be another issue at hand. Will update once I know what it is, i think it's another AWT-related incompatibility.

**Comment by griffin4cats** [comment] 2021-08-19 01:18
Update: ToroHealth Damage Indicators is currently incompatible, but unascribed has now made a [pull request to ToroHealth](https://github.com/ToroCraft/ToroHealth/pull/120) that will fix the incompatibility, so this is no longer an issue on 1.17.1. If I find any more AWT incompatibilities I'll update this further, but the backrooms related AWT error still stands.

**Comment by magneticflux-** [comment] 2021-08-19 05:05
Does #33 not work anymore? I'll have to revisit my hack and see if I can make it more effective.

It might be that including `optifabric` will activate my workaround and fix the mods. @griffin4cats Can you test that?

**Comment by griffin4cats** [comment] 2021-08-24 22:48
The thing is, I never included optifabric in that modpack, but that section of code seemed to activate from what I saw when i was working with a friend to figure out the incompatibility.

**Comment by magneticflux-** [comment] 2021-08-24 23:03
Maybe making the workaround more aggressive will help. @griffin4cats Can you test this version to see if it fixes the issues? (Unzip first)
[fabric-mumblelink-mod-0.8.4.zip](https://github.com/magneticflux-/fabric-mumblelink-mod/files/7042538/fabric-mumblelink-mod-0.8.4.zip)

**Comment by griffin4cats** [comment] 2021-08-26 23:36
The backrooms incompatibility occured in 1.16.5 which is no longer supported by mumblelink. The backrooms does not have a 1.17 version yet. I thought I mentioned that it was in 1.16.5, but i guess I forgot to.

**Comment by magneticflux-** [comment] 2021-09-05 07:02
I'm closing this issue in favor of #78 to centralize all info about AWT-using mods.

**Closed as completed by magneticflux-** 2021-09-05 07:02 UTC
Labels: bug, question
