### ISSUE TITLE
Crash upon joining sever

### ISSUE THREAD

**Issue by StormPrime** [magneticflux-/fabric-mumblelink-mod#66] opened 2021-04-07 20:30 UTC
Whenever I join a server it says this as a crash error

```
java.lang.LinkageError: loader constraint violation: when resolving interface method "com.sun.jna.platform.win32.Kernel32.MapViewOfFile(Lcom/sun/jna/platform/win32/WinNT$HANDLE;IIII)Lcom/sun/jna/Pointer;" the class loader (instance of net/fabricmc/loader/launch/knot/KnotClassLoader) of the current class, com/skaggsm/mumblelinkmod/shaded/sharedmemory/win32/SharedMemoryWin32, and the class loader (instance of java/net/URLClassLoader) for the method's defining class, com/sun/jna/platform/win32/WinNT, have different Class objects for the type com/sun/jna/Pointer used in the signature
	at com.skaggsm.mumblelinkmod.shaded.sharedmemory.win32.SharedMemoryWin32.<init>(SharedMemoryWin32.java:30)
	at com.skaggsm.mumblelinkmod.shaded.sharedmemory.SharedMemory.getSharedMemory(SharedMemory.java:32)
	at com.skaggsm.mumblelinkmod.shaded.jmumblelink.MumbleLinkImpl.<init>(MumbleLinkImpl.java:16)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod.ensureLinked(ClientMumbleLinkMod.java:109)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod.access$ensureLinked(ClientMumbleLinkMod.java:35)
	at com.skaggsm.mumblelinkmod.ClientMumbleLinkMod$onInitializeClient$2.onStartTick(ClientMumbleLinkMod.java:68)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents$$Lambda$5251/1706854837.onStartTick(Unknown Source)
	at net.minecraft.class_310.handler$ecb000$onStartTick(class_310.java:23381)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1364913072.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```

**Comment by magneticflux-** [comment] 2021-04-07 20:32
Duplicate of #64

**Closed as completed by magneticflux-** 2021-04-07 20:32 UTC
