### ISSUE TITLE
CrossTalk log spam in TeamSpeak "invalid clientID"

### ISSUE THREAD

**Issue by Lazare-C** [magneticflux-/fabric-mumblelink-mod#20] opened 2020-01-06 21:18 UTC
Teamspeak spam: `CrossTalk: PositionalAudio: (GetSendStringJson): invalid clientID`
in 1.14.4

**Comment by magneticflux-** [comment] 2020-01-06 21:23
It seems to be an issue in CrossTalk [here](https://forum.teamspeak.com/threads/141458-I-get-an-error-message-when-other-people-talk) or [here](https://github.com/thorwe/CrossTalk/issues/2). What version of TeamSpeak and CrossTalk are you using?

**Comment by PhilippKochendoerfer** [comment] 2020-03-05 12:16
same problem

MC: 1.15.2
TS: 3.3.0  (18.06.2019 11:29:01)
CT: 1.8.0

Windows 10

**Comment by magneticflux-** [comment] 2020-03-05 23:21
I built a version of the CrossTalk plugin with some more debug info and I'll try to reproduce this issue.

**Comment by magneticflux-** [comment] 2020-03-05 23:35
I am unable to reproduce this with a local client and server. I can't fix your issues without TeamSpeak and/or Minecraft logs to see what is going wrong.

**Comment by PhilippKochendoerfer** [comment] 2020-03-06 00:33
Teamspeak: (i censored the Numbers)

```
06.03.2020 00:22:24	CrossTalk	Info	PositionalAudio: New context: 4d696e65637261xxxx	
06.03.2020 00:22:24	CrossTalk	Info	PositionalAudio: New identity: 9c0413dc-a755-388b-bf60-xxx
06.03.2020 00:22:24	CrossTalk	Error	(TSHelpers::GetClientUID): invalid clientID	
06.03.2020 00:22:24	CrossTalk	Error	(TsVrObjOther::TsVrObjOther): invalid clientID	
06.03.2020 00:22:24	CrossTalk	Debug	PositionalAudio: Received: VR: Minecraft Mumble Link Mod CO: match ID: 9c0413dc-a755-388b-bf60-xxx	
06.03.2020 00:22:24	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:24	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:24	CrossTalk	Debug	PositionalAudio: Received: VR: Minecraft Mumble Link Mod CO: match ID: 9c0413dc-a755-388b-bf60-xxx	
06.03.2020 00:22:24	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:24	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:31	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:31	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:41	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:41	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:44	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:44	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:47	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:47	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:48	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:48	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:48	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:48	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:52	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:52	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:55	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:55	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:58	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:58	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:58	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:58	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:59	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:59	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:59	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:59	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:59	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:59	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:22:59	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:22:59	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:00	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:00	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:00	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:00	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:01	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:01	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:01	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:01	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:02	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:02	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:02	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:02	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:03	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:03	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:04	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:04	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:04	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:04	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:04	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:04	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:05	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:05	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:05	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:05	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:05	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:05	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:06	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:06	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:06	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:06	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:06	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:06	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:10	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:10	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:15	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:15	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:19	CrossTalk	Error	PositionalAudio: (GetSendStringJson): invalid clientID	
06.03.2020 00:23:19	CrossTalk	Warning	TSLogging::PlayErrorSound:Unknown Custom Error (GetSoundPack) Unknown error.	
06.03.2020 00:23:31	CrossTalk	Info	PositionalAudio: Unlocked.	
```

Minecraft:
```
[01:21:18] [main/INFO]: Loading for game Minecraft 1.15.2
[01:21:22] [main/INFO]: [FabricLoader] Loading 44 mods: minecraft@1.15.2, fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-keybindings-v0@0.1.1+dfdb52d60c, fabricloader@0.7.8+build.184, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.3, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.61, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.2.4+203491ea0c, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.2.7+a1bd31180c, fabric-language-kotlin@1.3.61+build.1, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, cloth-config2@2.5.3, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.3, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-resource-loader-v0@0.1.10+06c939b30c, autoconfig1u@1.2.4, fabric-textures-v0@1.0.4+821cdba70c, org_jetbrains_kotlin_kotlin-reflect@1.3.61, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-commands-v0@0.1.2+b7f9825d0c, org_jetbrains_kotlin_kotlin-stdlib@1.3.61, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.61, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric@0.4.32+build.292-1.15, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, fabric-networking-v0@0.1.7+12515ed90c, fabric-mumblelink-mod@0.6.1, org_jetbrains_annotations@17.0.0
[01:21:27] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/User/Downloads/mmc-stable-win32/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[01:21:29] [main/INFO]: Setting user: USERNAME
[01:21:39] [main/INFO]: [Indigo] Registering Indigo renderer!
[01:21:39] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[01:21:45] [main/INFO]: Narrator library for x64 successfully loaded
[01:21:45] [main/INFO]: Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Networking Block Entity (v0), Fabric Key Bindings (v0), Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Biomes (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Language Kotlin, Fabric API Base, Fabric Rendering (v0), Fabric Rendering (v1), Cloth Config v2, Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Auto Config v1 Updated, Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Rendering Fluids (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Fabric BlockRenderLayer Registration (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Events Lifecycle (v0), Fabric Loot Tables (v1), Fabric API, Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0), Fabric Networking (v0), MumbleLink
[01:21:57] [main/INFO]: OpenAL initialized.
[01:21:57] [main/INFO]: Sound engine started
[01:21:57] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[01:21:57] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[01:21:57] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[01:21:57] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[01:21:57] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[01:21:57] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[01:21:57] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[01:21:58] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[01:21:58] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[01:21:58] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[01:22:17] [main/INFO]: Connecting to localhost, 25565
[01:22:23] [main/INFO]: Loaded 84 advancements
[01:22:24] [main/INFO]: Linking to VoIP client...
[01:22:24] [main/INFO]: Linked
[01:23:12] [main/INFO]: [CHAT] <USERNAME> test
[01:23:22] [main/INFO]: Unlinking from VoIP client...
[01:23:22] [main/INFO]: Unlinked
```



Maybe its a user error ?

**Comment by magneticflux-** [comment] 2020-03-06 03:29
@PhilippKochendoerfer 
I have two ideas to try:

1. Only use the default "Sound Pack" on TeamSpeak and see if the error still occurs. I'm not sure what sound packs are since I don't use TeamSpeak frequently, but it's appearing alongside the error. If this is the problem, it's probably and issue with CrossTalk itself.
2. Try my debug build of CrossTalk and send new logs. I'll attach a binary that you can install manually, and a patch that you can apply to the CrossTalk sources if you wish to build it yourself.

Here's a zip file containing a pre-built x86_64 binary and a patch to build it from source: [CrossTalk_debug.zip](https://github.com/magneticflux-/fabric-mumblelink-mod/files/4296276/CrossTalk_debug.zip)

I've traced out the source of the error as far as I can right now and I can't find any location in which my mod's data could be used to affect what's causing the error. It appears like the `clientID` values are passed to the plugin from TeamSpeak and sent directly through to `GetSendStringJson`.

Here's the path that I traced out:
```
on_plugin_command(uint64 sch_id, const char * plugin_name, const char * plugin_command, anyID invoker_client_id, const char * invoker_name, const char * invoker_uid) (Plugin)
    onPluginCommand(uint64 serverConnectionHandlerID, anyID clientID, bool isMe, QString cmd, QTextStream & args) (PositionalAudio)
        Add(uint64 serverConnectionHandlerID, anyID clientID) (TsVrUniverse)
            TsVrObjOther(QObject * parent, uint64 serverConnectionHandlerID, anyID clientID) (TsVrObjOther)
                GetClientUID(uint64 serverConnectionHandlerID, anyID clientID, QString & result) (TSHelpers)
                GetSendStringJson(bool isAll, bool isMe, TsVrObj * obj) (PositionalAudio)
```

**Comment by magneticflux-** [comment] 2020-03-06 16:01
@thorwe, do you have any insight into this issue? Is there something wrong with my implementation?

**Comment by thorwe** [comment] 2020-03-08 08:52
I changed the protocol for the API 23 where it's not necessary anymore to
pass the client id manually without adding legacy support.
Most likely there's a mix of different Crosstalk versions involved. Make
sure they're all using 1.8.0 from
https://www.myteamspeak.com/addons/9ddfa0b2-25c2-4302-8a43-07f8819af9a9
Error should go away then.

**Comment by magneticflux-** [comment] 2020-03-08 19:11
@thorwe 
Thanks for the help!

@Lazare-C @PhilippKochendoerfer 
Please try again using the latest versions of TeamSpeak and CrossTalk, and make sure the other members also use the latest versions too.

If it appears that updating fixes the issue or there's no new activity in a few days, I'll close this as resolved.

**Comment by thorwe** [comment] 2020-03-09 05:23
I figure I may have been a bit cryptic in my answer, so just for the record in more detail:
In API 23 TS added clientId of the sender to the plugin command event (https://github.com/thorwe/CrossTalk/commit/85533c553b9faf2d35cb21a436a0b326e59b3b21#diff-36167d09070ef0224839f96a1f443a1eL226), before that I encoded the client id into the string that gets send (https://github.com/thorwe/CrossTalk/commit/85533c553b9faf2d35cb21a436a0b326e59b3b21#diff-4d7e408a05b400ecc33508eaadf190c6L911) and parsed it on the receiver (https://github.com/thorwe/CrossTalk/commit/85533c553b9faf2d35cb21a436a0b326e59b3b21#diff-36167d09070ef0224839f96a1f443a1eL248).
Little thought was admittedly given about backwards compatibility...
However, a CrossTalk version <1.8.0 will still try to read the client id out of the string, which will fail if the string got composed by the latest version - which sounds suspiciously like the issue reported.

**Comment by magneticflux-** [comment] 2020-03-12 17:38
Closing as it seems the issue is resolved. Feel free to comment/reopen if there are still issues after following @thorwe's advice!

**Closed as completed by magneticflux-** 2020-03-12 17:38 UTC
Labels: question
