### ISSUE TITLE
Not working with OptiFine + OptiFabric

### ISSUE THREAD

**Issue by devkarthin** [magneticflux-/fabric-mumblelink-mod#32] opened 2020-10-23 23:32 UTC
Game hangs for several minutes when launching this mod with OptiFine + OptiFabric (and never finishes from what I can tell). [Here](https://hastebin.com/visobopezi) are the logs. Running macOS using MultiMC as the launcher. Game runs after disabling MumbleLink or after disabling OptiFine + OptiFabric.

**Comment by magneticflux-** [comment] 2020-10-24 04:42
Can you post your log somewhere else? Hastebin is returning a 503 Service Unavailable error when I try to look at your logs (https://hastebin.com/documents/visobopezi).

**Comment by devkarthin** [comment] 2020-10-24 04:54
https://gist.github.com/devkarthin/d6cc0fbb36a11224ff07ea72662b8cf9

**Comment by magneticflux-** [comment] 2020-10-24 04:58
Just to confirm, it works with just MumbleLink and no OptiFabric/Optifine?

**Comment by devkarthin** [comment] 2020-10-24 04:58
Yes. It works with just MumbleLink.

**Comment by magneticflux-** [comment] 2020-10-24 05:06
I'll try to reproduce on Windows, otherwise I'll post a debug build with extra logging for you to try since I don't have easy access to a macOS computer.

**Comment by magneticflux-** [comment] 2020-10-24 08:39
I don't think it's possible to be a Mixin conflict because it's localized to just macOS. That implies it's an issue with MumbleLink's memory access, which is the only other thing that is complicated enough to cause issues.

Can you clone/download these two dependent libraries and run `./gradlew test` inside them?
- https://github.com/magneticflux-/jvm-shared-memory
- https://github.com/magneticflux-/java-mumble-link

That *should* rule out any memory access issues, because the tests create and destroy tons of mapped memory sections and test reads/writes to them.

**Comment by devkarthin** [comment] 2020-10-24 20:04
Sure, here are the logs:
[jvm-shared-memory](https://gist.github.com/devkarthin/51423ec4d38b4a75472a761792b85921)
[java-mumble-link](https://gist.github.com/devkarthin/53cb0aade1c83e3f0681628ecfb71551)

**Comment by magneticflux-** [comment] 2020-10-25 00:30
That's very strange, there seem to be no issues with memory access. Here's a build of MumbleLink with extra logging so we can figure out exactly when it hangs.

Download, extract the zip to get the jar inside, add to your mods folder like normal, and post the logs with MumbleLink alone and with MumbleLink and OptiFabric/Optifine. Debug logging build: [fabric-mumblelink-mod-0.7.4-debug-logging.zip](https://github.com/magneticflux-/fabric-mumblelink-mod/files/5433976/fabric-mumblelink-mod-0.7.4-debug-logging.zip)

**Comment by devkarthin** [comment] 2020-10-25 01:29
* [Log without OptiFine + OptiFabric](https://gist.github.com/devkarthin/f7ac02358c31d6fbb39a726515a326ae)
* [Log with OptiFine + OptiFabric](https://gist.github.com/devkarthin/d8c3a439eb394307a8d6d26c8751b5f5)

**Comment by magneticflux-** [comment] 2020-10-25 04:29
It seems like MumbleLink is initializing properly and the issue occurs in OptiFine code. From that I'm inclined to direct you to OptiFabric's issue tracker if I can't find anything else: https://github.com/Chocohead/OptiFabric/issues/81.

Can you post your log of just starting OptiFabric+OptiFine, no MumbleLink? It seems like OptiFine is hanging at the point where it generates mipmaps (just after BetterGrass is initialized). That could mean graphics driver issues (your build of macOS is quite old, 10.15 Catalina is latest).

**Comment by Chocohead** [comment] 2020-10-25 15:09
Following through what OptiFine is doing, try changing the mipmapping to 0 (`mipmapLevels` in the normal `options.txt` file). It looks like OptiFine is using AWT's `Dimension` class as part of working out the minimum atlas sprite size, some how getting away with it normally given OptiFine is clearly more generally working on MacOS otherwise, but not liking the fact Mumblelink sets the graphics environment to not be headless. Of course this is predicated on OptiFine working for you on its own, but it is from OptiFine using `Dimension` which is the cause of the freezing either way.

**Comment by devkarthin** [comment] 2020-10-25 16:17
Changing the mipmap levels to 0 seems to make the game load. Thanks!

**Comment by Chocohead** [comment] 2020-10-25 19:54
Might have to see if I can fudge something with OptiFabric to make it work with a mipmapping > 3. Should probably report it to OptiFine too though as it shouldn't really be using `Dimension` in the first place.

**Comment by magneticflux-** [comment] 2020-10-25 23:31
Since it seems pretty clear that OptiFine is improperly using AWT's `Dimension` class and since MumbleLink requires `java.awt.headless=false` to be able to open URIs, I'm closing this issue in favor of the OptiFabric issue and I'll put all of the relevant information there.

**Closed as completed by magneticflux-** 2020-10-25 23:31 UTC
Labels: question
