### ISSUE TITLE
Crash loading singleplayer w/ fabric-language-scala

### ISSUE THREAD

**Issue by AmyMialee** [magneticflux-/fabric-mumblelink-mod#67] opened 2021-05-03 00:08 UTC
[crash-2021-05-03_01.06.55-client.txt](https://github.com/magneticflux-/fabric-mumblelink-mod/files/6412487/crash-2021-05-03_01.06.55-client.txt)

**Comment by magneticflux-** [comment] 2021-05-03 01:03
Duplicate of #64

**Closed as completed by magneticflux-** 2021-05-03 01:03 UTC
